WITH settlement_updates (
    settlement_id,
    utility2_type,
    healer_on_entered,
    healer_on_healed,
    healer_on_cured,
    utility2_on_entered,
    utility2_on_placed,
    utility2_on_action
) AS (
    VALUES
    (1, 'trainer',
     'Mind the sway. Sit where the ropes cross and I can see what the ravine has done to you.',
     'That should hold. Favor the other side until the bruising stops arguing with the plankwork.',
     'Mist fever breaks when you stop pretending the cold is only in your coat.',
     'Feet first, eyes up. Rookbridge kills the people who only watch the boards beneath them.',
     'The practice lines are tied. If the knot slips, you learned too late.',
     'Again. The ravine gives no credit for almost balanced.'),
    (2, 'church',
     'Keep to the lit side of the room. If the Vault has followed you home, it can wait outside my lamps.',
     'You are breathing evenly again. That matters more than what the corridor wanted from you.',
     'The metallic taste will pass. Do not drink from any channel that hums back.',
     'Quiet hands. Quiet steps. We do not worship the Vault, but we do not shout at it either.',
     'The ward lamps are placed. Leave them burning until the room remembers us as residents.',
     'Name three things you know are yours. Good. Now keep walking.'),
    (3, 'blacksmith',
     'Come in from the wind. Cliff coughs leave grit deeper than the throat.',
     'Bandaged and braced. You can work, but not on the exposed channel walk today.',
     'Burrow rot is out. Burn those gloves before you touch another root bed.',
     'If a brace looks temporary, it is already late. Tell me which terrace needs iron.',
     'The retaining pins are set. If the wall keeps whispering soil, call the water crew.',
     'Hammer once for fit, twice for warning, never a third time unless you want the cliff to answer.'),
    (4, 'trainer',
     'You smell like deep channel water. Sit down before the shaking becomes a habit.',
     'The reed cuts are clean now. Keep them dry, which I know is rude advice in Brackwater.',
     'Bloom sickness is stubborn. If the colors brighten again, come back before you start admiring them.',
     'Skiff pole low, shoulders loose. The wetland moves first; you answer second.',
     'The marker flags are set through the fog flats. Follow touch when sight starts lying.',
     'Again from the dock. If you fall in, climb out on the downstream side.'),
    (5, 'blacksmith',
     'Steam burns hide under the skin. Let me cool it before you decide you are fine.',
     'The blistering is sealed. Stay away from the mineral flats until the wrap stops tightening.',
     'Sulfur cough clears slowly. Breathe through cloth when the vents start tasting sweet.',
     'Heat is a tool only while it is contained. Bring me any gauge that twitches twice.',
     'The vent clamps are seated. If they sing, back away before admiring the sound.',
     'Quench, check, then move. Therm Vale rewards patience and punishes curiosity.'),
    (6, 'alchemist',
     'The hives are restless today. Sit by the herb table and keep your voice low.',
     'Honey, comfrey, clean linen. Not holy, just effective.',
     'The forest rash is fading. Do not scratch when it starts feeling like bark.',
     'Medicine grows here if we ask correctly and harvest gently.',
     'The tinctures are set beside the hive rows. Take the amber bottle only after meals.',
     'A cure that strips the root bare is not a cure we can afford.'),
    (7, 'trainer',
     'Bridge legs, friend. Sit before your knees remember the drop.',
     'You can cross again when the spinning stops. Spanreach has enough falling objects.',
     'Cable rust poisoning is ugly, but early treatment keeps it merely embarrassing.',
     'Traffic moves because people know where to stand. Learn that before learning how to fight.',
     'The drill markers are painted along the main span. Stay between them when carts pass.',
     'Again with the pack on. Balance without cargo is just confidence.'),
    (8, 'alchemist',
     'Those scratches are not from ordinary thorn. Let me see the color at the edges.',
     'The poultice will sting. If it stops stinging too soon, call me.',
     'Redgrove venom likes to wait. This draught teaches it impatience.',
     'The forest gives medicine and bait in the same leaf. Know which you are holding.',
     'The scent masks are mixed. Wear one before crossing fresh spoor.',
     'Grind with the grain of the bark, not against it, unless you enjoy wasting cures.'),
    (9, 'enchanter',
     'Your eyes are tracking waves that are not there. Sit where the shore stays still.',
     'The vertigo will ease when the charm stops pulling. Do not row until then.',
     'Lake chill cures poorly unless you convince the bones they are back on land.',
     'Greyfen lies with horizons. These knots remember which way is shore.',
     'The anchor charm is fixed to the oarlock. It will tug when the sky reflection turns wrong.',
     'Listen for the hum. If it falls silent, stop rowing and count your hands.'),
    (10, 'enchanter',
     'Do not worry. Everyone feels sick the first time the ground thinks beneath them.',
     'The bruises are simple. The motion sickness is not. I treated both.',
     'Gear fever clears when the pulse stops syncing with the tread.',
     'Karth moves through pressure, rhythm, and refusal. I only negotiate the first two.',
     'The stabilizing mark is set. If it warms, the tread is about to disagree with us.',
     'Touch the rail and count the beats. If the count changes, so has the settlement.'),
    (11, 'alchemist',
     'Breathe shallow until the pollen settles. The garden likes attention too much.',
     'The swelling is down. Keep the salve covered, or the vines will treat it as an invitation.',
     'Spore bloom is gone. Burn the cloth outside the walls.',
     'Life returns to mixtures as readily as soil. Our task is choosing how much.',
     'The reliquary draught is ready. One sip, not two; reverence is not dosage.',
     'If the mixture sprouts, it is not ruined. It is warning you.'),
    (12, 'blacksmith',
     'Ash in the lungs, cracked feet, old cuts reopened. The March keeps a tidy ledger.',
     'You can walk. You cannot run. Fortunately, persisting is slower than fleeing.',
     'The ember infection is out. Keep the wound away from campfire smoke tonight.',
     'Portable does not mean fragile. Bring me buckles that survive panic.',
     'The field anvil is staked. Repairs happen before dawn or after distance.',
     'Strike clean, pack fast. The best tool is the one still usable when the camp moves.'),
    (13, 'church',
     'Sit near the wall. The mountain takes enough from people who insist on standing.',
     'Wrapped tight. Give the ankle one day before testing whether gravity has forgiven you.',
     'Altitude fever has broken. Drink slowly and stop challenging the air.',
     'A cairn is a promise that someone measured the fall and kept climbing.',
     'The trail blessing is placed at the step stones. Touch it only if you mean to continue.',
     'Speak the name of the ledge before crossing. Memory is cheaper than rescue.'),
    (14, 'enchanter',
     'You came in with gravewind on your coat. Sit by the warm stones until it leaves.',
     'The wound is closed. The ache may stay; some places insist on being remembered.',
     'Cairn chill is lifted. If you hear your name from outside, do not answer tonight.',
     'Names hold better in stone when the wind is given something else to steal.',
     'The remembrance mark is set. It will fade when the dead stop pulling at it.',
     'Do not polish the rune smooth. Rough edges are how memory grips.'),
    (15, 'blacksmith',
     'Do not touch the mechanism in your sleeve. Yes, I can hear it clicking.',
     'Patched, cleaned, braced. Sunkreach has damaged sturdier things than you.',
     'Ruin dust sickness clears if caught before the teeth start buzzing.',
     'Everything here needs a brace, including confidence.',
     'The stabilizer frame is fitted. If the floor sinks, it will complain before it fails.',
     'Tighten in sequence. The city punishes shortcuts with architecture.'),
    (16, 'blacksmith',
     'Hold still. I know that is unpopular here, but the splinter is moving with you.',
     'The wrap flexes. You can climb, carefully, which I know means quickly to you people.',
     'Rope-burn fever is gone. Replace the lashing that gave it to you.',
     'A joint that never shifts is either perfect or dangerous. I prepare for both.',
     'The counterweight hook is set. Move it only after the wind changes twice.',
     'Light tools, strong bites. The Spire hates heavy answers.'),
    (17, 'alchemist',
     'Look at my hand, not your shadow. Good. Now tell me how many fingers stayed still.',
     'The light strain is easing. Rest somewhere with ordinary lamps if you can find such luxury.',
     'Brightness sickness drains out slowly. Keep the dark cloth over your eyes until the afterimages stop.',
     'Light pools, dust settles, mixtures remember. Measure before the glow starts persuading you.',
     'The stabilizing wash is ready for the lantern glass. Do not stare into it while it cools.',
     'If the powder shines upward, seal the jar and step away.')
)
UPDATE game.world_info w
SET
    healer_asset_id = 14,
    healer_on_entered = jsonb_build_array(u.healer_on_entered),
    healer_on_healed = jsonb_build_array(u.healer_on_healed),
    healer_on_cured = jsonb_build_array(u.healer_on_cured),
    healer_msg_rect = COALESCE(w.healer_msg_rect, '{"x1":4.97,"y1":5.86,"x2":65.15,"y2":24.27}'::jsonb),
    utility2_type = u.utility2_type,
    utility2_asset_id = 14,
    utility2_on_entered = jsonb_build_array(u.utility2_on_entered),
    utility2_on_placed = jsonb_build_array(u.utility2_on_placed),
    utility2_on_action = jsonb_build_array(u.utility2_on_action),
    utility2_msg_rect = COALESCE(w.utility2_msg_rect, '{"x1":3.79,"y1":4.21,"x2":77.28,"y2":23.44}'::jsonb),
    blacksmith = w.blacksmith OR u.utility2_type = 'blacksmith',
    alchemist = w.alchemist OR u.utility2_type = 'alchemist',
    enchanter = w.enchanter OR u.utility2_type = 'enchanter',
    trainer = w.trainer OR u.utility2_type = 'trainer',
    church = w.church OR u.utility2_type = 'church',
    blacksmith_asset_id = CASE WHEN u.utility2_type = 'blacksmith' THEN COALESCE(w.blacksmith_asset_id, 14) ELSE w.blacksmith_asset_id END,
    alchemist_asset_id = CASE WHEN u.utility2_type = 'alchemist' THEN COALESCE(w.alchemist_asset_id, 14) ELSE w.alchemist_asset_id END,
    enchanter_asset_id = CASE WHEN u.utility2_type = 'enchanter' THEN COALESCE(w.enchanter_asset_id, 14) ELSE w.enchanter_asset_id END,
    trainer_asset_id = CASE WHEN u.utility2_type = 'trainer' THEN COALESCE(w.trainer_asset_id, 14) ELSE w.trainer_asset_id END,
    church_asset_id = CASE WHEN u.utility2_type = 'church' THEN COALESCE(w.church_asset_id, 14) ELSE w.church_asset_id END,
    version = (SELECT COALESCE(MAX(version), 0) + 1 FROM game.world_info)
FROM settlement_updates u
WHERE w.settlement_id = u.settlement_id;
