-- Recreate expedition tables inside the game schema so they mirror tooling
-- (minus the tooling-only pos_x/pos_y/slide_state columns) and add
-- server-side bookkeeping columns.

DROP TABLE IF EXISTS game.expedition_outcomes CASCADE;
DROP TABLE IF EXISTS game.expedition_options CASCADE;
DROP TABLE IF EXISTS game.expedition_slides CASCADE;

CREATE TABLE game.expedition_slides (
    slide_id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slide_text         text NOT NULL,
    asset_id           integer NOT NULL,
    effect_id          integer,
    effect_factor      integer,
    is_start           boolean NOT NULL DEFAULT false,
    settlement_id      smallint,
    reward_stat_type   varchar,
    reward_stat_amount integer,
    reward_talent      boolean,
    reward_item        integer REFERENCES game.items(item_id),
    reward_perk        smallint REFERENCES game.perks_info(perk_id),
    reward_blessing    smallint REFERENCES game.perks_info(perk_id),
    reward_potion      integer REFERENCES game.items(item_id),
    reward_silver      integer,
    is_deleted         boolean NOT NULL DEFAULT false,
    version            integer NOT NULL DEFAULT 1
);

CREATE TABLE game.expedition_options (
    option_id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slide_id         integer NOT NULL REFERENCES game.expedition_slides(slide_id) ON DELETE CASCADE,
    option_text      text NOT NULL,
    stat_type        varchar,
    stat_required    integer,
    effect_id        integer,
    effect_amount    integer,
    enemy_id         integer,
    faction_required text,
    silver_required  integer
);

CREATE TABLE game.expedition_outcomes (
    outcome_id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    option_id       integer NOT NULL REFERENCES game.expedition_options(option_id) ON DELETE CASCADE,
    target_slide_id integer NOT NULL REFERENCES game.expedition_slides(slide_id)
);
